# Generated by Django 3.0.6 on 2020-05-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_person_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='state',
            field=models.CharField(default='Mbola tsy vita', max_length=250),
        ),
    ]
