# Generated by Django 3.0.6 on 2020-05-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_request_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='requests/'),
        ),
        migrations.AlterField(
            model_name='area',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Office'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_at', to='base.Area'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
